import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {cn} from "@/lib/utils";
import { Toaster } from "@/components/ui/sonner";
import { dbConnect } from "@/service/mongo";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "My Learning Nextjs Project",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {

  const conn = await dbConnect();
  

  return (
    <html lang="en">
      <body
        className={cn(`${geistSans.variable} ${geistMono.variable} antialiased`)}
      >
        {children}
        <Toaster richColors position="top-center" />
      </body>
    </html>
  );
}
